### ISSUE TITLE
Bindings fail to build when cross-compiling for armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by affenull2345** [kaiostech/api-daemon#3]
I'm using clang and lld to cross-compile the B2G simulator for an ARM Linux machine. The API daemon fails to build because `support/libsignal-sys/build.sh` and `third-party/breakpad_sys/build.sh` only support cross-compiling for Android, but not for other targets. There should at least be the option to set the CC, CXX, CXXFLAGS and CFLAGS environment variables

After patching libsignal-sys, I get errors about breakpad such as the following:
```
  = note: ld.lld: error: .../api-daemon/target/armv7-unknown-linux-gnueabihf/debug/deps/libbreakpad_sys-f3889a38ba5ce939.rlib(exception_handler.o) is incompatible with elf32-littlearm
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by affenull2345** [comment]
After patching libsignal-sys, I get the following error message from breakpad
```
ld.lld: error: /home/bookfinch/3.0-build-kaiosrt/services/api-daemon/target/armv7-unknown-linux-gnueabihf/debug/deps/libbreakpad_sys-f3889a38ba5ce939.rlib(rust_breakpad_linux.o) is incompatible with elf32-littlearm
```
because it uses the host system's C compiler.

**Comment by fabricedesre** [comment]
For ld, did you change the linker definition that is generated into `.cargo/config` by the `utils.sh` script?

The fork at https://github.com/capyloon/api-daemon has support to cross-compile for more targets but with both breakpad and libsignal disabled by default.

**Comment by affenull2345** [comment]
I just used `cargo build --target=armv7-unknown-linux-gnueabihf` and set `RUSTFLAGS` for the linker config. And I guess I don't really need libsignal and breakpad enabled. I'll try out that fork, thanks!
