### ISSUE TITLE
API Daemon issue when building kaiostech/B2G

### ISSUE THREAD

**Issue by DiegoAscanio** [kaiostech/api-daemon#4]
Whenever I'm trying to build kaiostech/B2G an issue appears during the build process (build.sh)

It reaches 73% progress during compilation but the following error is issued:

`[ 73% 183/248] including gonk-misc/Android.mk ...
FAILED: 
gonk-misc/api-daemon/Android.mk: error: api-daemon: No source files specified`
`build/make/core/prebuilt_internal.mk:38: error: done.`
`17:04:48 ckati failed with: exit status 1`

Reading gonk-misc/api-daemon/Android.mk I see that it tries to find some source files supposedly fetched by cargo.

But these files do not appear neither in api-daemon dir, or in mozbuild.

During ./mach bootstrap in gecko dir after chosing either option 4 ( GeckoView/Firefox for Android Artifact Mode) or 5 (GeckoView/Firefox for Android) it fetches all required sources from kaios tech repos (I updated LOCAL_NDK_BASE_URL to https://packages.preprod.kaiostech.com/ndk/android-ndk) and also downloaded mozbuild from https://packages.preprod.kaiostech.com/ndk/v7/mozbuild.tar.bz2 and extracted it to the home dir of my building environment (as it is should be located there).

I can't understand why this error keeps happening but I think I might have a clue. During ./mach bootstrap inside gecko dir, after git-cinnabar prompt, it tries to fetch code from somewhere but it can't succeed as seen here:

![image](https://user-images.githubusercontent.com/6247962/222820610-80fbc660-e350-4c29-a839-ae7f946787c6.png)

I think that the code bootstrap tries to fetch are exactly the missing source codes in gonk-misc/api-daemon/Android.mk. But I don't where to take it or how I'd by pass this bootstrap step and put these files manually in required dirs, so my build process would happen smoothly.

For complementary information, I'm using rust version 1.56.1 as recommended in [here](https://github.com/kaiostech/gecko-b2g/issues/58). But no matter what I do this error keeps happening. Could someone help me in explaining what am I doing wrong? I'd deeply appreciate and thanks in advance!

With my best regards, Diego Ascânio Santos

**Comment by fabricedesre** [comment]
Hi Diego,

Sorry about that. I don't think anyone actively maintains these builds. The one that are known to work are in the capyloon fork at https://github.com/capyloon/B2G . Both the GSI and Sargo images are built on a regular basis. For which device are you trying to build?

**Comment by DiegoAscanio** [comment]
I'm trying to build for x86_64 emulator. If I use B2G from capyloon and gecko-b2g from kaios would I  build an emulator with KaiOS appearance?

I actually ran KaiOS 2.5 Simulator, but it ain't the same thing as the emulator. Through emulator I'd be able to experiment some stuff with esoteric devices and accessories. 

Thanks for your answer Fabrice!

**Comment by fabricedesre** [comment]
gecko-b2g in capyloon is a fork of the one from kaios, with some additions. So you should be good by just using capyloon/gecko-b2g

I have to admit that I never tried an emulator build from the capyloon repo, but that's something I would be willing to fix if that doesn't work.

**Comment by DiegoAscanio** [comment]
I'll try playing with capyloon. I really appreciate your explanations and help Fabrice! Thank you very much!

I'll try to build it for emulator and ask for your help if I'm stuck in something (:

**Comment by DiegoAscanio** [comment]
I'll try playing with capyloon. I really appreciate your explanations and help Fabrice! Thank you very much!

I'll try to build it for emulator and ask for your help if I'm stuck in something (:
